package globals

// TODO: parametre ucitavati iz config.yaml

const (
	// WAL
	WAL_PATH        = "resources\\wal.log"
	MAX_ENTRY_SIZE  = 1024
	CRC_SIZE        = 4
	TIMESTAMP_SIZE  = 8
	TOMBSTONE_SIZE  = 1
	KEY_SIZE_SIZE   = 8
	VALUE_SIZE_SIZE = 8

	CRC_START        = 0
	TIMESTAMP_START  = CRC_START + CRC_SIZE
	TOMBSTONE_START  = TIMESTAMP_START + TIMESTAMP_SIZE
	KEY_SIZE_START   = TOMBSTONE_START + TOMBSTONE_SIZE
	VALUE_SIZE_START = KEY_SIZE_START + KEY_SIZE_SIZE
	KEY_START        = VALUE_SIZE_START + VALUE_SIZE_SIZE

	// SKIP LIST
	SKIP_LIST_MAX_HEIGHT = 5

	// MEMTABLE
	MEMTABLE_STRUCTURE = "skiplist"
	MEMTABLE_MAX_SIZE  = 2
)
