# BLOOMFILTER
bloomExpectedElements : 1000
bloomFalsePositive : 0.0001

# CACHE
cacheCapacity : 100

# CMS
cmsEpsilon : 0.001
cmsDelta : 0.001

# MEMTABLE
memtableSize : 5
structureType : "skiplist"
skipListHeight : 5
bTreeOrder : 3

# TOKEN BUCKET
tokenNumber : 6
tokenRefreshTime : 2

# WAL
walPath : "resources\\wal.log"
maxEntrySize : 1024
crcSize : 4
timestampSize : 8
tombstoneSize : 1
keySizeSize : 8
valueSizeSize : 8
crcStart : 0