bloomExpectedElements: 1000
bloomFalsePositive: 0.001
cacheCapacity: 100
cmsEpsilon: 0.001
cmsDelta: 0.001
memtableSize: 10
structureType: skiplist
skipListHeight: 10
tokenNumber: 20
tokenRefreshTime: 2
walPath: resources\wal.log
maxEntrySize: 1024
crcSize: 4
timestampSize: 8
tombstoneSize: 1
keySizeSize: 8
valueSizeSize: 8
crcStart: 0
maxLevels: 4
maxBytes: 5000
maxTables: 2
scalingFactor: 2
compactionAlgorithm: sizeTiered
condition: tables
timestampStart: 4
tombstoneStart: 12
keySizeStart: 13
ValueSizeStart: 21
keyStart: 29
bTreeOrder: 3
