# BLOOMFILTER
bloomExpectedElements : 1000
bloomFalsePositive : 0.0001

# CACHE
cacheCapacity : 100

# CMS
cmsEpsilon : 0.001
cmsDelta : 0.001

# MEMTABLE
memtableSize : 5
structureType : "btree"
skipListHeight : 5
bTreeOrder : 3

# TOKEN BUCKET
tokenNumber : 6
tokenRefreshTime : 2

# WAL
walPath : "resources\\wal.log"
maxEntrySize : 1024
crcSize : 4
timestampSize : 8
tombstoneSize : 1
keySizeSize : 8
valueSizeSize : 8
crcStart : 0

# LSM TREE
maxLevels : 3 # Maksimalan broj nivoa
maxBytes : 5000 # Maksimalan broj bajtova na prvom nivou (broj se skalira za svaki nivo)
maxTables : 2 # Maksimalan broj ss tabela na prvom nivou (broj se skalira za svaki nivo)
scalingFactor : 2 # Broj koji mnozi maxTables i maxBytes po nivoima
compactionAlgorithm : "sizeTiered" # sizeTiered ili leveled
condition : "tables" # Uslov za pokretanje kompakcije (tables ili size)